### ISSUE TITLE
Linux fails to check for new version

### ISSUE THREAD

**Issue by edwanvi** [digiwombat/WorldMuncher#2]
When I start WorldMuncher, a box appears with the New World and Open World buttons (neither of which work), along with the text "Checking for New Version..."

I can exit that prompt, at which point I get [a lovely window where none of the buttons work.](http://imgur.com/a/1hwJP)

Presumably, this is dues to the program not being able to check for a new version. This might be due to a bug in the Linux version (it works fine on Windows), or an inability to check for new versions.

**Comment by edwanvi** [comment]
Just confirmed this is in fact something being wonky with the Linux version. Windows works fine without network access.

**Comment by digiwombat** [comment]
Yeah, this is a known issue possibly related to a native module (not sure, haven't tested yet). I tested Windows and Mac and both worked.

Can you check the .rpm version for me?

Also, sorry for the slow reply. I'm writing my new novel at the moment so I'm a bit swamped with that. Will 100% be fixing this in the next version. It MIGHT just be a build issue, so I will check that and update accordingly.

**Comment by edwanvi** [comment]
No, I can't check the rpm because I don't use fedora. If I get a few hours
of free time maybe.

**Comment by digiwombat** [comment]
No worries. I need to set up a fedora install at some point, but I've done some checking (hilarious timing, since I just clicked to address this), it's an electron-rebuild issue (module-mismatch).

Rebuilding now in Linux proper instead of using WSL, which seemed to be a large part of the problem, weirdly.

**Comment by digiwombat** [comment]
Builds updated. Linux builds work now.

Whew. Sorry, but hey! BashonUbuntuonWindows doesn't work for building these out it seems like.

EDIT: Also, if they don't work, please do re-open.

**Comment by edwanvi** [comment]
:tada:
